version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: email_generator_db
    environment:
      POSTGRES_DB: email_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - email_generator_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email_generator_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/email_generator
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - email_generator_network

  # Vite + React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email_generator_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - email_generator_network

volumes:
  postgres_data:

networks:
  email_generator_network:
    driver: bridge
